spring.application.name=frontal-sneakers-backend

# Configuração do H2 Database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração do DataSource (Conexão com o Banco)
spring.datasource.url=jdbc:h2:mem:frontalsneakersdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# Server
server.port=8080

# Debug
debug=true
